const dataArr = [
  {
    title: "Calculator",
    skillTags: ["Javascript"],
    text: "A simple calculator built using javascript functions interacting with the DOM. Next step is to add keyboard functionality.",
    gitHub: "https://github.com/jjgray90/js-calculator",
    liveSite: "https://jjgray90.github.io/js-calculator/",
    img: "assets/images/calculator.png",
    imgAlt: "Calculator",
  },
  {
    title: "Bojo Covo",
    skillTags: ["javascript"],
    text: "One lockdown weekend in March 2020, I decided to make a coronavirus version of space invaders. There are a couple of bugs I need to fix.",
    gitHub: "https://github.com/jjgray90/bojo-covo",
    liveSite: "https://bojo-covo.jjgray.me/",
    img: "assets/images/bojo-covo.png",
    imgAlt: "Screenshot of bojo covo game",
  },
  {
    title: "Punk API",
    skillTags: ["react"],
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi doloribus est aperiam fugiat aliquam duc.",
    gitHub: "https://github.com/jjgray90",
    liveSite: "https://jjgray90.github.io/oxna-portfolio/",
    img: "https://www.fillmurray.com/800/600",
    imgAlt: "Bill Murray",
  },
  {
    title: "Client Project",
    skillTags: ["react"],
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi doloribus est aperiam fugiat aliquam duc.",
    gitHub: "https://github.com/jjgray90",
    liveSite: "https://jjgray90.github.io/oxna-portfolio/",
    img: "https://www.fillmurray.com/300/400",
    imgAlt: "Bill Murray",
  },
  {
    title: "REST API",
    skillTags: ["java", "spring boot"],
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi doloribus est aperiam fugiat aliquam duc.",
    gitHub: "https://github.com/jjgray90",
    liveSite: "https://jjgray90.github.io/oxna-portfolio/",
    img: "https://www.fillmurray.com/900/500",
    imgAlt: "Bill Murray",
  },
  {
    title: "Punk API",
    skillTags: ["react"],
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi doloribus est aperiam fugiat aliquam duc.",
    gitHub: "https://github.com/jjgray90",
    liveSite: "https://jjgray90.github.io/oxna-portfolio/",
    img: "https://www.fillmurray.com/300/300",
    imgAlt: "Bill Murray",
  },
];

export default dataArr;
