const dataArr = [
  {
    title: "Client Project",
    skillTags: ["react"],
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi doloribus est aperiam fugiat aliquam duc.",
    gitHub: "https://github.com/jjgray90",
    liveSite: "https://jjgray90.github.io/oxna-portfolio/",
    img: "https://www.fillmurray.com/400/200",
    imgAlt: "Bill Murray",
  },
  {
    title: "REST API",
    skillTags: ["java", "spring boot"],
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi doloribus est aperiam fugiat aliquam duc.",
    gitHub: "https://github.com/jjgray90",
    liveSite: "https://jjgray90.github.io/oxna-portfolio/",
    img: "https://www.fillmurray.com/300/500",
    imgAlt: "Bill Murray",
  },
  {
    title: "Punk API",
    skillTags: ["react"],
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi doloribus est aperiam fugiat aliquam duc.",
    gitHub: "https://github.com/jjgray90",
    liveSite: "https://jjgray90.github.io/oxna-portfolio/",
    img: "https://www.fillmurray.com/800/600",
    imgAlt: "Bill Murray",
  },
  {
    title: "Client Project",
    skillTags: ["react"],
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi doloribus est aperiam fugiat aliquam duc.",
    gitHub: "https://github.com/jjgray90",
    liveSite: "https://jjgray90.github.io/oxna-portfolio/",
    img: "https://www.fillmurray.com/300/400",
    imgAlt: "Bill Murray",
  },
  {
    title: "REST API",
    skillTags: ["java", "spring boot"],
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi doloribus est aperiam fugiat aliquam duc.",
    gitHub: "https://github.com/jjgray90",
    liveSite: "https://jjgray90.github.io/oxna-portfolio/",
    img: "https://www.fillmurray.com/900/500",
    imgAlt: "Bill Murray",
  },
  {
    title: "Punk API",
    skillTags: ["react"],
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi doloribus est aperiam fugiat aliquam duc.",
    gitHub: "https://github.com/jjgray90",
    liveSite: "https://jjgray90.github.io/oxna-portfolio/",
    img: "https://www.fillmurray.com/300/300",
    imgAlt: "Bill Murray",
  },
];

export default dataArr;
